// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyA1AOAo-09D5jHpGguD7qBiyYG5zfWHBBo',
    appId: '1:1044926733751:web:0a3f74e01d4f9c3e6e5c32',
    messagingSenderId: '1044926733751',
    projectId: 'pmsn-p06',
    authDomain: 'pmsn-p06.firebaseapp.com',
    storageBucket: 'pmsn-p06.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDJKbYOqJwuZf4Tet6lxlRUmExsTVSAiUE',
    appId: '1:1044926733751:android:9e3dc21d313840006e5c32',
    messagingSenderId: '1044926733751',
    projectId: 'pmsn-p06',
    storageBucket: 'pmsn-p06.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDt-avG8DXk7_vRNAx1EE33QFvO8mgeDlc',
    appId: '1:1044926733751:ios:b8111a3dc264cf8a6e5c32',
    messagingSenderId: '1044926733751',
    projectId: 'pmsn-p06',
    storageBucket: 'pmsn-p06.appspot.com',
    iosBundleId: 'com.example.pmsn06',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDt-avG8DXk7_vRNAx1EE33QFvO8mgeDlc',
    appId: '1:1044926733751:ios:f8159a0a30f45b9a6e5c32',
    messagingSenderId: '1044926733751',
    projectId: 'pmsn-p06',
    storageBucket: 'pmsn-p06.appspot.com',
    iosBundleId: 'com.example.pmsn06.RunnerTests',
  );
}
